debug: false

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    accesslog:
      enabled: true
      directory: logs
spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
    cache: false    #页面不加载缓存，修改即时生效
  devtools:
    restart:
      enabled: true #设置开启热部署


